Added some debug output. Trying to change path so puppet will work.
found: /usr/bin/xcode-select
run: puppet apply deps.pp
/Users/travis/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- puppet/util/command_line (LoadError)
	from /Users/travis/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/bin/puppet:3:in `<main>'
Traceback (most recent call last):
  File "deps.py", line 205, in <module>
    sout = sp.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['puppet', 'apply', 'deps.pp']' returned non-zero exit status 1

refs #87